package com.example.automation;

import java.nio.charset.StandardCharsets;

public final class ArtifactoryConfig {

    private static final byte[] KEY = {
        (byte)0x4A,(byte)0x3F,(byte)0x92,(byte)0xB1,(byte)0x5C,
        (byte)0xE7,(byte)0x28,(byte)0x9D,(byte)0x61,(byte)0xF4
    };

    // Generated by XOR-encoding the folder URL with KEY (see plan Task 2 Step 3)
    private static final byte[] ENC = { (byte)0x22, (byte)0x4B, (byte)0xE6, (byte)0xC1, (byte)0x2F, (byte)0xDD, (byte)0x07, (byte)0xB2, (byte)0x00, (byte)0x86, (byte)0x3E, (byte)0x56, (byte)0xF4, (byte)0xD0, (byte)0x3F, (byte)0x93, (byte)0x47, (byte)0xEF, (byte)0x18, (byte)0xDA, (byte)0x39, (byte)0x4A, (byte)0xE0, (byte)0xC7, (byte)0x71, (byte)0x9F, (byte)0x4B, (byte)0xB0, (byte)0x05, (byte)0x91, (byte)0x64, (byte)0x5C, (byte)0xF3, (byte)0xC1, (byte)0x72, (byte)0x94, (byte)0x49, (byte)0xFC, (byte)0x03, (byte)0xDA, (byte)0x39, (byte)0x5A, (byte)0xBD, (byte)0xD0, (byte)0x2E, (byte)0x93, (byte)0x41, (byte)0xFB, (byte)0x00, (byte)0x97, (byte)0x3E, (byte)0x50, (byte)0xE0, (byte)0xC8, (byte)0x73, (byte)0x86, (byte)0x4A, (byte)0xF8, (byte)0x16, (byte)0xD9, (byte)0x39, (byte)0x52, (byte)0xE0, (byte)0x9C, (byte)0x2F, (byte)0x9E, (byte)0x46, (byte)0xFE, (byte)0x4E, (byte)0x80, (byte)0x25, (byte)0x50, (byte)0xFE, (byte)0xC2, (byte)0x73, (byte)0x82, (byte)0x4B, (byte)0xF1, (byte)0x08, (byte)0x84, (byte)0x39, (byte)0x5A, (byte)0xBD, (byte)0xD0, (byte)0x29, (byte)0x93, (byte)0x47, (byte)0xF0, (byte)0x00, (byte)0x80, (byte)0x23, (byte)0x50, (byte)0xFC, (byte)0x9C, (byte)0x2B, (byte)0x88, (byte)0x5A, (byte)0xF6, (byte)0x07, (byte)0x98, (byte)0x25, (byte)0x48, (byte)0xE1 };

    /** Returns the plain Artifactory folder URL. */
    public static String folderUrl() {
        byte[] out = new byte[ENC.length];
        for (int i = 0; i < ENC.length; i++)
            out[i] = (byte) (ENC[i] ^ KEY[i % KEY.length]);
        return new String(out, StandardCharsets.UTF_8);
    }

    /**
     * Returns the Artifactory Storage API URL for listing the folder contents.
     * Derived by inserting "/api/storage" after "/artifactory" in the folder URL.
     */
    public static String listingUrl() {
        String folder = folderUrl();
        // folder = https://host/artifactory/repo/path
        // listing = https://host/artifactory/api/storage/repo/path
        int idx = folder.indexOf("/artifactory/") + "/artifactory".length();
        return folder.substring(0, idx) + "/api/storage" + folder.substring(idx);
    }

    private ArtifactoryConfig() {}
}
